// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/mazu-kubernetes-podwatcher-raw.proto

package podmsgraw;

public final class MazuRecordRaw {
  private MazuRecordRaw() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PodMessageRawOrBuilder extends
      // @@protoc_insertion_point(interface_extends:podmsgraw.PodMessageRaw)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pod_name = 1;</code>
     * @return The podName.
     */
    java.lang.String getPodName();
    /**
     * <code>string pod_name = 1;</code>
     * @return The bytes for podName.
     */
    com.google.protobuf.ByteString
        getPodNameBytes();

    /**
     * <code>int64 start_time = 2;</code>
     * @return The startTime.
     */
    long getStartTime();

    /**
     * <code>int64 end_time = 3;</code>
     * @return The endTime.
     */
    long getEndTime();

    /**
     * <pre>
     * CPU - MilliValue
     * </pre>
     *
     * <code>int64 cpu_requested = 4;</code>
     * @return The cpuRequested.
     */
    long getCpuRequested();

    /**
     * <pre>
     * GPU - MilliValue
     * </pre>
     *
     * <code>int64 gpu_requested = 5;</code>
     * @return The gpuRequested.
     */
    long getGpuRequested();

    /**
     * <pre>
     * Memory - Value
     * </pre>
     *
     * <code>int64 memory_requested = 6;</code>
     * @return The memoryRequested.
     */
    long getMemoryRequested();

    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */
    int getLabelsCount();
    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */
    boolean containsLabels(
        java.lang.String key);
    /**
     * Use {@link #getLabelsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getLabels();
    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getLabelsMap();
    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */

    java.lang.String getLabelsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */

    java.lang.String getLabelsOrThrow(
        java.lang.String key);

    /**
     * <pre>
     * data ingestion time
     * </pre>
     *
     * <code>int64 ingestion_time = 8;</code>
     * @return The ingestionTime.
     */
    long getIngestionTime();
  }
  /**
   * <pre>
   * The PodMessageRaw containing message sending to API Gateway =&gt; Kinesis DS =&gt; Kinesis FH =&gt; S3
   * </pre>
   *
   * Protobuf type {@code podmsgraw.PodMessageRaw}
   */
  public  static final class PodMessageRaw extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:podmsgraw.PodMessageRaw)
      PodMessageRawOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PodMessageRaw.newBuilder() to construct.
    private PodMessageRaw(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PodMessageRaw() {
      podName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PodMessageRaw();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PodMessageRaw(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              podName_ = s;
              break;
            }
            case 16: {

              startTime_ = input.readInt64();
              break;
            }
            case 24: {

              endTime_ = input.readInt64();
              break;
            }
            case 32: {

              cpuRequested_ = input.readInt64();
              break;
            }
            case 40: {

              gpuRequested_ = input.readInt64();
              break;
            }
            case 48: {

              memoryRequested_ = input.readInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                labels_ = com.google.protobuf.MapField.newMapField(
                    LabelsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              labels__ = input.readMessage(
                  LabelsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              labels_.getMutableMap().put(
                  labels__.getKey(), labels__.getValue());
              break;
            }
            case 64: {

              ingestionTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetLabels();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              podmsgraw.MazuRecordRaw.PodMessageRaw.class, podmsgraw.MazuRecordRaw.PodMessageRaw.Builder.class);
    }

    public static final int POD_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object podName_;
    /**
     * <code>string pod_name = 1;</code>
     * @return The podName.
     */
    public java.lang.String getPodName() {
      java.lang.Object ref = podName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        podName_ = s;
        return s;
      }
    }
    /**
     * <code>string pod_name = 1;</code>
     * @return The bytes for podName.
     */
    public com.google.protobuf.ByteString
        getPodNameBytes() {
      java.lang.Object ref = podName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        podName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_TIME_FIELD_NUMBER = 2;
    private long startTime_;
    /**
     * <code>int64 start_time = 2;</code>
     * @return The startTime.
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int END_TIME_FIELD_NUMBER = 3;
    private long endTime_;
    /**
     * <code>int64 end_time = 3;</code>
     * @return The endTime.
     */
    public long getEndTime() {
      return endTime_;
    }

    public static final int CPU_REQUESTED_FIELD_NUMBER = 4;
    private long cpuRequested_;
    /**
     * <pre>
     * CPU - MilliValue
     * </pre>
     *
     * <code>int64 cpu_requested = 4;</code>
     * @return The cpuRequested.
     */
    public long getCpuRequested() {
      return cpuRequested_;
    }

    public static final int GPU_REQUESTED_FIELD_NUMBER = 5;
    private long gpuRequested_;
    /**
     * <pre>
     * GPU - MilliValue
     * </pre>
     *
     * <code>int64 gpu_requested = 5;</code>
     * @return The gpuRequested.
     */
    public long getGpuRequested() {
      return gpuRequested_;
    }

    public static final int MEMORY_REQUESTED_FIELD_NUMBER = 6;
    private long memoryRequested_;
    /**
     * <pre>
     * Memory - Value
     * </pre>
     *
     * <code>int64 memory_requested = 6;</code>
     * @return The memoryRequested.
     */
    public long getMemoryRequested() {
      return memoryRequested_;
    }

    public static final int LABELS_FIELD_NUMBER = 7;
    private static final class LabelsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_LabelsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> labels_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetLabels() {
      if (labels_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LabelsDefaultEntryHolder.defaultEntry);
      }
      return labels_;
    }

    public int getLabelsCount() {
      return internalGetLabels().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */

    public boolean containsLabels(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetLabels().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLabelsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getLabels() {
      return getLabelsMap();
    }
    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getLabelsMap() {
      return internalGetLabels().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */

    public java.lang.String getLabelsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLabels().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; labels = 7;</code>
     */

    public java.lang.String getLabelsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLabels().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int INGESTION_TIME_FIELD_NUMBER = 8;
    private long ingestionTime_;
    /**
     * <pre>
     * data ingestion time
     * </pre>
     *
     * <code>int64 ingestion_time = 8;</code>
     * @return The ingestionTime.
     */
    public long getIngestionTime() {
      return ingestionTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, podName_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(2, startTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(3, endTime_);
      }
      if (cpuRequested_ != 0L) {
        output.writeInt64(4, cpuRequested_);
      }
      if (gpuRequested_ != 0L) {
        output.writeInt64(5, gpuRequested_);
      }
      if (memoryRequested_ != 0L) {
        output.writeInt64(6, memoryRequested_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetLabels(),
          LabelsDefaultEntryHolder.defaultEntry,
          7);
      if (ingestionTime_ != 0L) {
        output.writeInt64(8, ingestionTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, podName_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endTime_);
      }
      if (cpuRequested_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, cpuRequested_);
      }
      if (gpuRequested_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, gpuRequested_);
      }
      if (memoryRequested_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, memoryRequested_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetLabels().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        labels__ = LabelsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, labels__);
      }
      if (ingestionTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, ingestionTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof podmsgraw.MazuRecordRaw.PodMessageRaw)) {
        return super.equals(obj);
      }
      podmsgraw.MazuRecordRaw.PodMessageRaw other = (podmsgraw.MazuRecordRaw.PodMessageRaw) obj;

      if (!getPodName()
          .equals(other.getPodName())) return false;
      if (getStartTime()
          != other.getStartTime()) return false;
      if (getEndTime()
          != other.getEndTime()) return false;
      if (getCpuRequested()
          != other.getCpuRequested()) return false;
      if (getGpuRequested()
          != other.getGpuRequested()) return false;
      if (getMemoryRequested()
          != other.getMemoryRequested()) return false;
      if (!internalGetLabels().equals(
          other.internalGetLabels())) return false;
      if (getIngestionTime()
          != other.getIngestionTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPodName().hashCode();
      hash = (37 * hash) + START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + END_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      hash = (37 * hash) + CPU_REQUESTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCpuRequested());
      hash = (37 * hash) + GPU_REQUESTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGpuRequested());
      hash = (37 * hash) + MEMORY_REQUESTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemoryRequested());
      if (!internalGetLabels().getMap().isEmpty()) {
        hash = (37 * hash) + LABELS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetLabels().hashCode();
      }
      hash = (37 * hash) + INGESTION_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIngestionTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(podmsgraw.MazuRecordRaw.PodMessageRaw prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The PodMessageRaw containing message sending to API Gateway =&gt; Kinesis DS =&gt; Kinesis FH =&gt; S3
     * </pre>
     *
     * Protobuf type {@code podmsgraw.PodMessageRaw}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:podmsgraw.PodMessageRaw)
        podmsgraw.MazuRecordRaw.PodMessageRawOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetLabels();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableLabels();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                podmsgraw.MazuRecordRaw.PodMessageRaw.class, podmsgraw.MazuRecordRaw.PodMessageRaw.Builder.class);
      }

      // Construct using podmsgraw.MazuRecordRaw.PodMessageRaw.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        podName_ = "";

        startTime_ = 0L;

        endTime_ = 0L;

        cpuRequested_ = 0L;

        gpuRequested_ = 0L;

        memoryRequested_ = 0L;

        internalGetMutableLabels().clear();
        ingestionTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_descriptor;
      }

      @java.lang.Override
      public podmsgraw.MazuRecordRaw.PodMessageRaw getDefaultInstanceForType() {
        return podmsgraw.MazuRecordRaw.PodMessageRaw.getDefaultInstance();
      }

      @java.lang.Override
      public podmsgraw.MazuRecordRaw.PodMessageRaw build() {
        podmsgraw.MazuRecordRaw.PodMessageRaw result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public podmsgraw.MazuRecordRaw.PodMessageRaw buildPartial() {
        podmsgraw.MazuRecordRaw.PodMessageRaw result = new podmsgraw.MazuRecordRaw.PodMessageRaw(this);
        int from_bitField0_ = bitField0_;
        result.podName_ = podName_;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        result.cpuRequested_ = cpuRequested_;
        result.gpuRequested_ = gpuRequested_;
        result.memoryRequested_ = memoryRequested_;
        result.labels_ = internalGetLabels();
        result.labels_.makeImmutable();
        result.ingestionTime_ = ingestionTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof podmsgraw.MazuRecordRaw.PodMessageRaw) {
          return mergeFrom((podmsgraw.MazuRecordRaw.PodMessageRaw)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(podmsgraw.MazuRecordRaw.PodMessageRaw other) {
        if (other == podmsgraw.MazuRecordRaw.PodMessageRaw.getDefaultInstance()) return this;
        if (!other.getPodName().isEmpty()) {
          podName_ = other.podName_;
          onChanged();
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        if (other.getCpuRequested() != 0L) {
          setCpuRequested(other.getCpuRequested());
        }
        if (other.getGpuRequested() != 0L) {
          setGpuRequested(other.getGpuRequested());
        }
        if (other.getMemoryRequested() != 0L) {
          setMemoryRequested(other.getMemoryRequested());
        }
        internalGetMutableLabels().mergeFrom(
            other.internalGetLabels());
        if (other.getIngestionTime() != 0L) {
          setIngestionTime(other.getIngestionTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        podmsgraw.MazuRecordRaw.PodMessageRaw parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (podmsgraw.MazuRecordRaw.PodMessageRaw) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object podName_ = "";
      /**
       * <code>string pod_name = 1;</code>
       * @return The podName.
       */
      public java.lang.String getPodName() {
        java.lang.Object ref = podName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          podName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pod_name = 1;</code>
       * @return The bytes for podName.
       */
      public com.google.protobuf.ByteString
          getPodNameBytes() {
        java.lang.Object ref = podName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          podName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pod_name = 1;</code>
       * @param value The podName to set.
       * @return This builder for chaining.
       */
      public Builder setPodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        podName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pod_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPodName() {
        
        podName_ = getDefaultInstance().getPodName();
        onChanged();
        return this;
      }
      /**
       * <code>string pod_name = 1;</code>
       * @param value The bytes for podName to set.
       * @return This builder for chaining.
       */
      public Builder setPodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        podName_ = value;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>int64 start_time = 2;</code>
       * @return The startTime.
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>int64 start_time = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 start_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>int64 end_time = 3;</code>
       * @return The endTime.
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>int64 end_time = 3;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 end_time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private long cpuRequested_ ;
      /**
       * <pre>
       * CPU - MilliValue
       * </pre>
       *
       * <code>int64 cpu_requested = 4;</code>
       * @return The cpuRequested.
       */
      public long getCpuRequested() {
        return cpuRequested_;
      }
      /**
       * <pre>
       * CPU - MilliValue
       * </pre>
       *
       * <code>int64 cpu_requested = 4;</code>
       * @param value The cpuRequested to set.
       * @return This builder for chaining.
       */
      public Builder setCpuRequested(long value) {
        
        cpuRequested_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CPU - MilliValue
       * </pre>
       *
       * <code>int64 cpu_requested = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuRequested() {
        
        cpuRequested_ = 0L;
        onChanged();
        return this;
      }

      private long gpuRequested_ ;
      /**
       * <pre>
       * GPU - MilliValue
       * </pre>
       *
       * <code>int64 gpu_requested = 5;</code>
       * @return The gpuRequested.
       */
      public long getGpuRequested() {
        return gpuRequested_;
      }
      /**
       * <pre>
       * GPU - MilliValue
       * </pre>
       *
       * <code>int64 gpu_requested = 5;</code>
       * @param value The gpuRequested to set.
       * @return This builder for chaining.
       */
      public Builder setGpuRequested(long value) {
        
        gpuRequested_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * GPU - MilliValue
       * </pre>
       *
       * <code>int64 gpu_requested = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGpuRequested() {
        
        gpuRequested_ = 0L;
        onChanged();
        return this;
      }

      private long memoryRequested_ ;
      /**
       * <pre>
       * Memory - Value
       * </pre>
       *
       * <code>int64 memory_requested = 6;</code>
       * @return The memoryRequested.
       */
      public long getMemoryRequested() {
        return memoryRequested_;
      }
      /**
       * <pre>
       * Memory - Value
       * </pre>
       *
       * <code>int64 memory_requested = 6;</code>
       * @param value The memoryRequested to set.
       * @return This builder for chaining.
       */
      public Builder setMemoryRequested(long value) {
        
        memoryRequested_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Memory - Value
       * </pre>
       *
       * <code>int64 memory_requested = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemoryRequested() {
        
        memoryRequested_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> labels_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetLabels() {
        if (labels_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              LabelsDefaultEntryHolder.defaultEntry);
        }
        return labels_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableLabels() {
        onChanged();;
        if (labels_ == null) {
          labels_ = com.google.protobuf.MapField.newMapField(
              LabelsDefaultEntryHolder.defaultEntry);
        }
        if (!labels_.isMutable()) {
          labels_ = labels_.copy();
        }
        return labels_;
      }

      public int getLabelsCount() {
        return internalGetLabels().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; labels = 7;</code>
       */

      public boolean containsLabels(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetLabels().getMap().containsKey(key);
      }
      /**
       * Use {@link #getLabelsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getLabels() {
        return getLabelsMap();
      }
      /**
       * <code>map&lt;string, string&gt; labels = 7;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getLabelsMap() {
        return internalGetLabels().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; labels = 7;</code>
       */

      public java.lang.String getLabelsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetLabels().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; labels = 7;</code>
       */

      public java.lang.String getLabelsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetLabels().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearLabels() {
        internalGetMutableLabels().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; labels = 7;</code>
       */

      public Builder removeLabels(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableLabels().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableLabels() {
        return internalGetMutableLabels().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; labels = 7;</code>
       */
      public Builder putLabels(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableLabels().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; labels = 7;</code>
       */

      public Builder putAllLabels(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableLabels().getMutableMap()
            .putAll(values);
        return this;
      }

      private long ingestionTime_ ;
      /**
       * <pre>
       * data ingestion time
       * </pre>
       *
       * <code>int64 ingestion_time = 8;</code>
       * @return The ingestionTime.
       */
      public long getIngestionTime() {
        return ingestionTime_;
      }
      /**
       * <pre>
       * data ingestion time
       * </pre>
       *
       * <code>int64 ingestion_time = 8;</code>
       * @param value The ingestionTime to set.
       * @return This builder for chaining.
       */
      public Builder setIngestionTime(long value) {
        
        ingestionTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * data ingestion time
       * </pre>
       *
       * <code>int64 ingestion_time = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIngestionTime() {
        
        ingestionTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:podmsgraw.PodMessageRaw)
    }

    // @@protoc_insertion_point(class_scope:podmsgraw.PodMessageRaw)
    private static final podmsgraw.MazuRecordRaw.PodMessageRaw DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new podmsgraw.MazuRecordRaw.PodMessageRaw();
    }

    public static podmsgraw.MazuRecordRaw.PodMessageRaw getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PodMessageRaw>
        PARSER = new com.google.protobuf.AbstractParser<PodMessageRaw>() {
      @java.lang.Override
      public PodMessageRaw parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PodMessageRaw(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PodMessageRaw> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PodMessageRaw> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public podmsgraw.MazuRecordRaw.PodMessageRaw getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_podmsgraw_PodMessageRaw_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_podmsgraw_PodMessageRaw_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_podmsgraw_PodMessageRaw_LabelsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_podmsgraw_PodMessageRaw_LabelsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.resources/mazu-kubernetes-podwatcher-r" +
      "aw.proto\022\tpodmsgraw\032-github.com/gogo/pro" +
      "tobuf/gogoproto/gogo.proto\"\214\002\n\rPodMessag" +
      "eRaw\022\020\n\010pod_name\030\001 \001(\t\022\022\n\nstart_time\030\002 \001" +
      "(\003\022\020\n\010end_time\030\003 \001(\003\022\025\n\rcpu_requested\030\004 " +
      "\001(\003\022\025\n\rgpu_requested\030\005 \001(\003\022\030\n\020memory_req" +
      "uested\030\006 \001(\003\0224\n\006labels\030\007 \003(\0132$.podmsgraw" +
      ".PodMessageRaw.LabelsEntry\022\026\n\016ingestion_" +
      "time\030\010 \001(\003\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\t:\0028\001B\017B\rMazuRecordRawb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_podmsgraw_PodMessageRaw_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_podmsgraw_PodMessageRaw_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_podmsgraw_PodMessageRaw_descriptor,
        new java.lang.String[] { "PodName", "StartTime", "EndTime", "CpuRequested", "GpuRequested", "MemoryRequested", "Labels", "IngestionTime", });
    internal_static_podmsgraw_PodMessageRaw_LabelsEntry_descriptor =
      internal_static_podmsgraw_PodMessageRaw_descriptor.getNestedTypes().get(0);
    internal_static_podmsgraw_PodMessageRaw_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_podmsgraw_PodMessageRaw_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
