// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/mazu-kubernetes-podwatcher-raw.proto

package podmsgraw;

public final class MazuRecordRaw {
  private MazuRecordRaw() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PodMessageRawOrBuilder extends
      // @@protoc_insertion_point(interface_extends:podmsgraw.PodMessageRaw)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pod_name = 1;</code>
     * @return The podName.
     */
    java.lang.String getPodName();
    /**
     * <code>string pod_name = 1;</code>
     * @return The bytes for podName.
     */
    com.google.protobuf.ByteString
        getPodNameBytes();

    /**
     * <code>string job_name = 2;</code>
     * @return The jobName.
     */
    java.lang.String getJobName();
    /**
     * <code>string job_name = 2;</code>
     * @return The bytes for jobName.
     */
    com.google.protobuf.ByteString
        getJobNameBytes();

    /**
     * <code>int64 start_time = 3;</code>
     * @return The startTime.
     */
    long getStartTime();

    /**
     * <code>int64 end_time = 4;</code>
     * @return The endTime.
     */
    long getEndTime();

    /**
     * <pre>
     * requested resources
     * </pre>
     *
     * <code>int64 cpu_requested = 5 [(.gogoproto.jsontag) = "cpu_requested"];</code>
     * @return The cpuRequested.
     */
    long getCpuRequested();

    /**
     * <pre>
     * GPU - MilliValue
     * </pre>
     *
     * <code>int64 gpu_requested = 6 [(.gogoproto.jsontag) = "gpu_requested"];</code>
     * @return The gpuRequested.
     */
    long getGpuRequested();

    /**
     * <pre>
     * Memory - Value
     * </pre>
     *
     * <code>int64 memory_requested = 7 [(.gogoproto.jsontag) = "memory_requested"];</code>
     * @return The memoryRequested.
     */
    long getMemoryRequested();

    /**
     * <pre>
     * derived values
     * </pre>
     *
     * <code>double cpu_cost = 8 [(.gogoproto.jsontag) = "cpu_cost"];</code>
     * @return The cpuCost.
     */
    double getCpuCost();

    /**
     * <code>double gpu_cost = 9 [(.gogoproto.jsontag) = "gpu_cost"];</code>
     * @return The gpuCost.
     */
    double getGpuCost();

    /**
     * <code>double memory_cost = 10 [(.gogoproto.jsontag) = "memory_cost"];</code>
     * @return The memoryCost.
     */
    double getMemoryCost();

    /**
     * <code>double multiplier = 11 [(.gogoproto.jsontag) = "multiplier"];</code>
     * @return The multiplier.
     */
    double getMultiplier();

    /**
     * <code>string owner = 12;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 12;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>string asset = 13;</code>
     * @return The asset.
     */
    java.lang.String getAsset();
    /**
     * <code>string asset = 13;</code>
     * @return The bytes for asset.
     */
    com.google.protobuf.ByteString
        getAssetBytes();

    /**
     * <code>string instance_type = 14;</code>
     * @return The instanceType.
     */
    java.lang.String getInstanceType();
    /**
     * <code>string instance_type = 14;</code>
     * @return The bytes for instanceType.
     */
    com.google.protobuf.ByteString
        getInstanceTypeBytes();

    /**
     * <code>string pricing_model = 15;</code>
     * @return The pricingModel.
     */
    java.lang.String getPricingModel();
    /**
     * <code>string pricing_model = 15;</code>
     * @return The bytes for pricingModel.
     */
    com.google.protobuf.ByteString
        getPricingModelBytes();

    /**
     * <pre>
     *int64 proc_time = 17; // processing time
     * </pre>
     *
     * <code>string cluster = 16;</code>
     * @return The cluster.
     */
    java.lang.String getCluster();
    /**
     * <pre>
     *int64 proc_time = 17; // processing time
     * </pre>
     *
     * <code>string cluster = 16;</code>
     * @return The bytes for cluster.
     */
    com.google.protobuf.ByteString
        getClusterBytes();
  }
  /**
   * Protobuf type {@code podmsgraw.PodMessageRaw}
   */
  public  static final class PodMessageRaw extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:podmsgraw.PodMessageRaw)
      PodMessageRawOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PodMessageRaw.newBuilder() to construct.
    private PodMessageRaw(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PodMessageRaw() {
      podName_ = "";
      jobName_ = "";
      owner_ = "";
      asset_ = "";
      instanceType_ = "";
      pricingModel_ = "";
      cluster_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PodMessageRaw();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PodMessageRaw(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              podName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              jobName_ = s;
              break;
            }
            case 24: {

              startTime_ = input.readInt64();
              break;
            }
            case 32: {

              endTime_ = input.readInt64();
              break;
            }
            case 40: {

              cpuRequested_ = input.readInt64();
              break;
            }
            case 48: {

              gpuRequested_ = input.readInt64();
              break;
            }
            case 56: {

              memoryRequested_ = input.readInt64();
              break;
            }
            case 65: {

              cpuCost_ = input.readDouble();
              break;
            }
            case 73: {

              gpuCost_ = input.readDouble();
              break;
            }
            case 81: {

              memoryCost_ = input.readDouble();
              break;
            }
            case 89: {

              multiplier_ = input.readDouble();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              asset_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              instanceType_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              pricingModel_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              cluster_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              podmsgraw.MazuRecordRaw.PodMessageRaw.class, podmsgraw.MazuRecordRaw.PodMessageRaw.Builder.class);
    }

    public static final int POD_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object podName_;
    /**
     * <code>string pod_name = 1;</code>
     * @return The podName.
     */
    public java.lang.String getPodName() {
      java.lang.Object ref = podName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        podName_ = s;
        return s;
      }
    }
    /**
     * <code>string pod_name = 1;</code>
     * @return The bytes for podName.
     */
    public com.google.protobuf.ByteString
        getPodNameBytes() {
      java.lang.Object ref = podName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        podName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOB_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object jobName_;
    /**
     * <code>string job_name = 2;</code>
     * @return The jobName.
     */
    public java.lang.String getJobName() {
      java.lang.Object ref = jobName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobName_ = s;
        return s;
      }
    }
    /**
     * <code>string job_name = 2;</code>
     * @return The bytes for jobName.
     */
    public com.google.protobuf.ByteString
        getJobNameBytes() {
      java.lang.Object ref = jobName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_TIME_FIELD_NUMBER = 3;
    private long startTime_;
    /**
     * <code>int64 start_time = 3;</code>
     * @return The startTime.
     */
    public long getStartTime() {
      return startTime_;
    }

    public static final int END_TIME_FIELD_NUMBER = 4;
    private long endTime_;
    /**
     * <code>int64 end_time = 4;</code>
     * @return The endTime.
     */
    public long getEndTime() {
      return endTime_;
    }

    public static final int CPU_REQUESTED_FIELD_NUMBER = 5;
    private long cpuRequested_;
    /**
     * <pre>
     * requested resources
     * </pre>
     *
     * <code>int64 cpu_requested = 5 [(.gogoproto.jsontag) = "cpu_requested"];</code>
     * @return The cpuRequested.
     */
    public long getCpuRequested() {
      return cpuRequested_;
    }

    public static final int GPU_REQUESTED_FIELD_NUMBER = 6;
    private long gpuRequested_;
    /**
     * <pre>
     * GPU - MilliValue
     * </pre>
     *
     * <code>int64 gpu_requested = 6 [(.gogoproto.jsontag) = "gpu_requested"];</code>
     * @return The gpuRequested.
     */
    public long getGpuRequested() {
      return gpuRequested_;
    }

    public static final int MEMORY_REQUESTED_FIELD_NUMBER = 7;
    private long memoryRequested_;
    /**
     * <pre>
     * Memory - Value
     * </pre>
     *
     * <code>int64 memory_requested = 7 [(.gogoproto.jsontag) = "memory_requested"];</code>
     * @return The memoryRequested.
     */
    public long getMemoryRequested() {
      return memoryRequested_;
    }

    public static final int CPU_COST_FIELD_NUMBER = 8;
    private double cpuCost_;
    /**
     * <pre>
     * derived values
     * </pre>
     *
     * <code>double cpu_cost = 8 [(.gogoproto.jsontag) = "cpu_cost"];</code>
     * @return The cpuCost.
     */
    public double getCpuCost() {
      return cpuCost_;
    }

    public static final int GPU_COST_FIELD_NUMBER = 9;
    private double gpuCost_;
    /**
     * <code>double gpu_cost = 9 [(.gogoproto.jsontag) = "gpu_cost"];</code>
     * @return The gpuCost.
     */
    public double getGpuCost() {
      return gpuCost_;
    }

    public static final int MEMORY_COST_FIELD_NUMBER = 10;
    private double memoryCost_;
    /**
     * <code>double memory_cost = 10 [(.gogoproto.jsontag) = "memory_cost"];</code>
     * @return The memoryCost.
     */
    public double getMemoryCost() {
      return memoryCost_;
    }

    public static final int MULTIPLIER_FIELD_NUMBER = 11;
    private double multiplier_;
    /**
     * <code>double multiplier = 11 [(.gogoproto.jsontag) = "multiplier"];</code>
     * @return The multiplier.
     */
    public double getMultiplier() {
      return multiplier_;
    }

    public static final int OWNER_FIELD_NUMBER = 12;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 12;</code>
     * @return The owner.
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 12;</code>
     * @return The bytes for owner.
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASSET_FIELD_NUMBER = 13;
    private volatile java.lang.Object asset_;
    /**
     * <code>string asset = 13;</code>
     * @return The asset.
     */
    public java.lang.String getAsset() {
      java.lang.Object ref = asset_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asset_ = s;
        return s;
      }
    }
    /**
     * <code>string asset = 13;</code>
     * @return The bytes for asset.
     */
    public com.google.protobuf.ByteString
        getAssetBytes() {
      java.lang.Object ref = asset_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTANCE_TYPE_FIELD_NUMBER = 14;
    private volatile java.lang.Object instanceType_;
    /**
     * <code>string instance_type = 14;</code>
     * @return The instanceType.
     */
    public java.lang.String getInstanceType() {
      java.lang.Object ref = instanceType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instanceType_ = s;
        return s;
      }
    }
    /**
     * <code>string instance_type = 14;</code>
     * @return The bytes for instanceType.
     */
    public com.google.protobuf.ByteString
        getInstanceTypeBytes() {
      java.lang.Object ref = instanceType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICING_MODEL_FIELD_NUMBER = 15;
    private volatile java.lang.Object pricingModel_;
    /**
     * <code>string pricing_model = 15;</code>
     * @return The pricingModel.
     */
    public java.lang.String getPricingModel() {
      java.lang.Object ref = pricingModel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pricingModel_ = s;
        return s;
      }
    }
    /**
     * <code>string pricing_model = 15;</code>
     * @return The bytes for pricingModel.
     */
    public com.google.protobuf.ByteString
        getPricingModelBytes() {
      java.lang.Object ref = pricingModel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pricingModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLUSTER_FIELD_NUMBER = 16;
    private volatile java.lang.Object cluster_;
    /**
     * <pre>
     *int64 proc_time = 17; // processing time
     * </pre>
     *
     * <code>string cluster = 16;</code>
     * @return The cluster.
     */
    public java.lang.String getCluster() {
      java.lang.Object ref = cluster_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cluster_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *int64 proc_time = 17; // processing time
     * </pre>
     *
     * <code>string cluster = 16;</code>
     * @return The bytes for cluster.
     */
    public com.google.protobuf.ByteString
        getClusterBytes() {
      java.lang.Object ref = cluster_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, podName_);
      }
      if (!getJobNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jobName_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(3, startTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(4, endTime_);
      }
      if (cpuRequested_ != 0L) {
        output.writeInt64(5, cpuRequested_);
      }
      if (gpuRequested_ != 0L) {
        output.writeInt64(6, gpuRequested_);
      }
      if (memoryRequested_ != 0L) {
        output.writeInt64(7, memoryRequested_);
      }
      if (cpuCost_ != 0D) {
        output.writeDouble(8, cpuCost_);
      }
      if (gpuCost_ != 0D) {
        output.writeDouble(9, gpuCost_);
      }
      if (memoryCost_ != 0D) {
        output.writeDouble(10, memoryCost_);
      }
      if (multiplier_ != 0D) {
        output.writeDouble(11, multiplier_);
      }
      if (!getOwnerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, owner_);
      }
      if (!getAssetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, asset_);
      }
      if (!getInstanceTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, instanceType_);
      }
      if (!getPricingModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, pricingModel_);
      }
      if (!getClusterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, cluster_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, podName_);
      }
      if (!getJobNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jobName_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, endTime_);
      }
      if (cpuRequested_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, cpuRequested_);
      }
      if (gpuRequested_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, gpuRequested_);
      }
      if (memoryRequested_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, memoryRequested_);
      }
      if (cpuCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, cpuCost_);
      }
      if (gpuCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, gpuCost_);
      }
      if (memoryCost_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, memoryCost_);
      }
      if (multiplier_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, multiplier_);
      }
      if (!getOwnerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, owner_);
      }
      if (!getAssetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, asset_);
      }
      if (!getInstanceTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, instanceType_);
      }
      if (!getPricingModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, pricingModel_);
      }
      if (!getClusterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, cluster_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof podmsgraw.MazuRecordRaw.PodMessageRaw)) {
        return super.equals(obj);
      }
      podmsgraw.MazuRecordRaw.PodMessageRaw other = (podmsgraw.MazuRecordRaw.PodMessageRaw) obj;

      if (!getPodName()
          .equals(other.getPodName())) return false;
      if (!getJobName()
          .equals(other.getJobName())) return false;
      if (getStartTime()
          != other.getStartTime()) return false;
      if (getEndTime()
          != other.getEndTime()) return false;
      if (getCpuRequested()
          != other.getCpuRequested()) return false;
      if (getGpuRequested()
          != other.getGpuRequested()) return false;
      if (getMemoryRequested()
          != other.getMemoryRequested()) return false;
      if (java.lang.Double.doubleToLongBits(getCpuCost())
          != java.lang.Double.doubleToLongBits(
              other.getCpuCost())) return false;
      if (java.lang.Double.doubleToLongBits(getGpuCost())
          != java.lang.Double.doubleToLongBits(
              other.getGpuCost())) return false;
      if (java.lang.Double.doubleToLongBits(getMemoryCost())
          != java.lang.Double.doubleToLongBits(
              other.getMemoryCost())) return false;
      if (java.lang.Double.doubleToLongBits(getMultiplier())
          != java.lang.Double.doubleToLongBits(
              other.getMultiplier())) return false;
      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!getAsset()
          .equals(other.getAsset())) return false;
      if (!getInstanceType()
          .equals(other.getInstanceType())) return false;
      if (!getPricingModel()
          .equals(other.getPricingModel())) return false;
      if (!getCluster()
          .equals(other.getCluster())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPodName().hashCode();
      hash = (37 * hash) + JOB_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getJobName().hashCode();
      hash = (37 * hash) + START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + END_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      hash = (37 * hash) + CPU_REQUESTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCpuRequested());
      hash = (37 * hash) + GPU_REQUESTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGpuRequested());
      hash = (37 * hash) + MEMORY_REQUESTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemoryRequested());
      hash = (37 * hash) + CPU_COST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCpuCost()));
      hash = (37 * hash) + GPU_COST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getGpuCost()));
      hash = (37 * hash) + MEMORY_COST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMemoryCost()));
      hash = (37 * hash) + MULTIPLIER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMultiplier()));
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + ASSET_FIELD_NUMBER;
      hash = (53 * hash) + getAsset().hashCode();
      hash = (37 * hash) + INSTANCE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceType().hashCode();
      hash = (37 * hash) + PRICING_MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getPricingModel().hashCode();
      hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
      hash = (53 * hash) + getCluster().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static podmsgraw.MazuRecordRaw.PodMessageRaw parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(podmsgraw.MazuRecordRaw.PodMessageRaw prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code podmsgraw.PodMessageRaw}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:podmsgraw.PodMessageRaw)
        podmsgraw.MazuRecordRaw.PodMessageRawOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                podmsgraw.MazuRecordRaw.PodMessageRaw.class, podmsgraw.MazuRecordRaw.PodMessageRaw.Builder.class);
      }

      // Construct using podmsgraw.MazuRecordRaw.PodMessageRaw.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        podName_ = "";

        jobName_ = "";

        startTime_ = 0L;

        endTime_ = 0L;

        cpuRequested_ = 0L;

        gpuRequested_ = 0L;

        memoryRequested_ = 0L;

        cpuCost_ = 0D;

        gpuCost_ = 0D;

        memoryCost_ = 0D;

        multiplier_ = 0D;

        owner_ = "";

        asset_ = "";

        instanceType_ = "";

        pricingModel_ = "";

        cluster_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return podmsgraw.MazuRecordRaw.internal_static_podmsgraw_PodMessageRaw_descriptor;
      }

      @java.lang.Override
      public podmsgraw.MazuRecordRaw.PodMessageRaw getDefaultInstanceForType() {
        return podmsgraw.MazuRecordRaw.PodMessageRaw.getDefaultInstance();
      }

      @java.lang.Override
      public podmsgraw.MazuRecordRaw.PodMessageRaw build() {
        podmsgraw.MazuRecordRaw.PodMessageRaw result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public podmsgraw.MazuRecordRaw.PodMessageRaw buildPartial() {
        podmsgraw.MazuRecordRaw.PodMessageRaw result = new podmsgraw.MazuRecordRaw.PodMessageRaw(this);
        result.podName_ = podName_;
        result.jobName_ = jobName_;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        result.cpuRequested_ = cpuRequested_;
        result.gpuRequested_ = gpuRequested_;
        result.memoryRequested_ = memoryRequested_;
        result.cpuCost_ = cpuCost_;
        result.gpuCost_ = gpuCost_;
        result.memoryCost_ = memoryCost_;
        result.multiplier_ = multiplier_;
        result.owner_ = owner_;
        result.asset_ = asset_;
        result.instanceType_ = instanceType_;
        result.pricingModel_ = pricingModel_;
        result.cluster_ = cluster_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof podmsgraw.MazuRecordRaw.PodMessageRaw) {
          return mergeFrom((podmsgraw.MazuRecordRaw.PodMessageRaw)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(podmsgraw.MazuRecordRaw.PodMessageRaw other) {
        if (other == podmsgraw.MazuRecordRaw.PodMessageRaw.getDefaultInstance()) return this;
        if (!other.getPodName().isEmpty()) {
          podName_ = other.podName_;
          onChanged();
        }
        if (!other.getJobName().isEmpty()) {
          jobName_ = other.jobName_;
          onChanged();
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        if (other.getCpuRequested() != 0L) {
          setCpuRequested(other.getCpuRequested());
        }
        if (other.getGpuRequested() != 0L) {
          setGpuRequested(other.getGpuRequested());
        }
        if (other.getMemoryRequested() != 0L) {
          setMemoryRequested(other.getMemoryRequested());
        }
        if (other.getCpuCost() != 0D) {
          setCpuCost(other.getCpuCost());
        }
        if (other.getGpuCost() != 0D) {
          setGpuCost(other.getGpuCost());
        }
        if (other.getMemoryCost() != 0D) {
          setMemoryCost(other.getMemoryCost());
        }
        if (other.getMultiplier() != 0D) {
          setMultiplier(other.getMultiplier());
        }
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (!other.getAsset().isEmpty()) {
          asset_ = other.asset_;
          onChanged();
        }
        if (!other.getInstanceType().isEmpty()) {
          instanceType_ = other.instanceType_;
          onChanged();
        }
        if (!other.getPricingModel().isEmpty()) {
          pricingModel_ = other.pricingModel_;
          onChanged();
        }
        if (!other.getCluster().isEmpty()) {
          cluster_ = other.cluster_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        podmsgraw.MazuRecordRaw.PodMessageRaw parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (podmsgraw.MazuRecordRaw.PodMessageRaw) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object podName_ = "";
      /**
       * <code>string pod_name = 1;</code>
       * @return The podName.
       */
      public java.lang.String getPodName() {
        java.lang.Object ref = podName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          podName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pod_name = 1;</code>
       * @return The bytes for podName.
       */
      public com.google.protobuf.ByteString
          getPodNameBytes() {
        java.lang.Object ref = podName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          podName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pod_name = 1;</code>
       * @param value The podName to set.
       * @return This builder for chaining.
       */
      public Builder setPodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        podName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pod_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPodName() {
        
        podName_ = getDefaultInstance().getPodName();
        onChanged();
        return this;
      }
      /**
       * <code>string pod_name = 1;</code>
       * @param value The bytes for podName to set.
       * @return This builder for chaining.
       */
      public Builder setPodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        podName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jobName_ = "";
      /**
       * <code>string job_name = 2;</code>
       * @return The jobName.
       */
      public java.lang.String getJobName() {
        java.lang.Object ref = jobName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string job_name = 2;</code>
       * @return The bytes for jobName.
       */
      public com.google.protobuf.ByteString
          getJobNameBytes() {
        java.lang.Object ref = jobName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string job_name = 2;</code>
       * @param value The jobName to set.
       * @return This builder for chaining.
       */
      public Builder setJobName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string job_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobName() {
        
        jobName_ = getDefaultInstance().getJobName();
        onChanged();
        return this;
      }
      /**
       * <code>string job_name = 2;</code>
       * @param value The bytes for jobName to set.
       * @return This builder for chaining.
       */
      public Builder setJobNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobName_ = value;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>int64 start_time = 3;</code>
       * @return The startTime.
       */
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>int64 start_time = 3;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 start_time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>int64 end_time = 4;</code>
       * @return The endTime.
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>int64 end_time = 4;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 end_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private long cpuRequested_ ;
      /**
       * <pre>
       * requested resources
       * </pre>
       *
       * <code>int64 cpu_requested = 5 [(.gogoproto.jsontag) = "cpu_requested"];</code>
       * @return The cpuRequested.
       */
      public long getCpuRequested() {
        return cpuRequested_;
      }
      /**
       * <pre>
       * requested resources
       * </pre>
       *
       * <code>int64 cpu_requested = 5 [(.gogoproto.jsontag) = "cpu_requested"];</code>
       * @param value The cpuRequested to set.
       * @return This builder for chaining.
       */
      public Builder setCpuRequested(long value) {
        
        cpuRequested_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * requested resources
       * </pre>
       *
       * <code>int64 cpu_requested = 5 [(.gogoproto.jsontag) = "cpu_requested"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuRequested() {
        
        cpuRequested_ = 0L;
        onChanged();
        return this;
      }

      private long gpuRequested_ ;
      /**
       * <pre>
       * GPU - MilliValue
       * </pre>
       *
       * <code>int64 gpu_requested = 6 [(.gogoproto.jsontag) = "gpu_requested"];</code>
       * @return The gpuRequested.
       */
      public long getGpuRequested() {
        return gpuRequested_;
      }
      /**
       * <pre>
       * GPU - MilliValue
       * </pre>
       *
       * <code>int64 gpu_requested = 6 [(.gogoproto.jsontag) = "gpu_requested"];</code>
       * @param value The gpuRequested to set.
       * @return This builder for chaining.
       */
      public Builder setGpuRequested(long value) {
        
        gpuRequested_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * GPU - MilliValue
       * </pre>
       *
       * <code>int64 gpu_requested = 6 [(.gogoproto.jsontag) = "gpu_requested"];</code>
       * @return This builder for chaining.
       */
      public Builder clearGpuRequested() {
        
        gpuRequested_ = 0L;
        onChanged();
        return this;
      }

      private long memoryRequested_ ;
      /**
       * <pre>
       * Memory - Value
       * </pre>
       *
       * <code>int64 memory_requested = 7 [(.gogoproto.jsontag) = "memory_requested"];</code>
       * @return The memoryRequested.
       */
      public long getMemoryRequested() {
        return memoryRequested_;
      }
      /**
       * <pre>
       * Memory - Value
       * </pre>
       *
       * <code>int64 memory_requested = 7 [(.gogoproto.jsontag) = "memory_requested"];</code>
       * @param value The memoryRequested to set.
       * @return This builder for chaining.
       */
      public Builder setMemoryRequested(long value) {
        
        memoryRequested_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Memory - Value
       * </pre>
       *
       * <code>int64 memory_requested = 7 [(.gogoproto.jsontag) = "memory_requested"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMemoryRequested() {
        
        memoryRequested_ = 0L;
        onChanged();
        return this;
      }

      private double cpuCost_ ;
      /**
       * <pre>
       * derived values
       * </pre>
       *
       * <code>double cpu_cost = 8 [(.gogoproto.jsontag) = "cpu_cost"];</code>
       * @return The cpuCost.
       */
      public double getCpuCost() {
        return cpuCost_;
      }
      /**
       * <pre>
       * derived values
       * </pre>
       *
       * <code>double cpu_cost = 8 [(.gogoproto.jsontag) = "cpu_cost"];</code>
       * @param value The cpuCost to set.
       * @return This builder for chaining.
       */
      public Builder setCpuCost(double value) {
        
        cpuCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * derived values
       * </pre>
       *
       * <code>double cpu_cost = 8 [(.gogoproto.jsontag) = "cpu_cost"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuCost() {
        
        cpuCost_ = 0D;
        onChanged();
        return this;
      }

      private double gpuCost_ ;
      /**
       * <code>double gpu_cost = 9 [(.gogoproto.jsontag) = "gpu_cost"];</code>
       * @return The gpuCost.
       */
      public double getGpuCost() {
        return gpuCost_;
      }
      /**
       * <code>double gpu_cost = 9 [(.gogoproto.jsontag) = "gpu_cost"];</code>
       * @param value The gpuCost to set.
       * @return This builder for chaining.
       */
      public Builder setGpuCost(double value) {
        
        gpuCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double gpu_cost = 9 [(.gogoproto.jsontag) = "gpu_cost"];</code>
       * @return This builder for chaining.
       */
      public Builder clearGpuCost() {
        
        gpuCost_ = 0D;
        onChanged();
        return this;
      }

      private double memoryCost_ ;
      /**
       * <code>double memory_cost = 10 [(.gogoproto.jsontag) = "memory_cost"];</code>
       * @return The memoryCost.
       */
      public double getMemoryCost() {
        return memoryCost_;
      }
      /**
       * <code>double memory_cost = 10 [(.gogoproto.jsontag) = "memory_cost"];</code>
       * @param value The memoryCost to set.
       * @return This builder for chaining.
       */
      public Builder setMemoryCost(double value) {
        
        memoryCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double memory_cost = 10 [(.gogoproto.jsontag) = "memory_cost"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMemoryCost() {
        
        memoryCost_ = 0D;
        onChanged();
        return this;
      }

      private double multiplier_ ;
      /**
       * <code>double multiplier = 11 [(.gogoproto.jsontag) = "multiplier"];</code>
       * @return The multiplier.
       */
      public double getMultiplier() {
        return multiplier_;
      }
      /**
       * <code>double multiplier = 11 [(.gogoproto.jsontag) = "multiplier"];</code>
       * @param value The multiplier to set.
       * @return This builder for chaining.
       */
      public Builder setMultiplier(double value) {
        
        multiplier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double multiplier = 11 [(.gogoproto.jsontag) = "multiplier"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMultiplier() {
        
        multiplier_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 12;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 12;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 12;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 12;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object asset_ = "";
      /**
       * <code>string asset = 13;</code>
       * @return The asset.
       */
      public java.lang.String getAsset() {
        java.lang.Object ref = asset_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          asset_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string asset = 13;</code>
       * @return The bytes for asset.
       */
      public com.google.protobuf.ByteString
          getAssetBytes() {
        java.lang.Object ref = asset_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          asset_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string asset = 13;</code>
       * @param value The asset to set.
       * @return This builder for chaining.
       */
      public Builder setAsset(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        asset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string asset = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearAsset() {
        
        asset_ = getDefaultInstance().getAsset();
        onChanged();
        return this;
      }
      /**
       * <code>string asset = 13;</code>
       * @param value The bytes for asset to set.
       * @return This builder for chaining.
       */
      public Builder setAssetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        asset_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object instanceType_ = "";
      /**
       * <code>string instance_type = 14;</code>
       * @return The instanceType.
       */
      public java.lang.String getInstanceType() {
        java.lang.Object ref = instanceType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instanceType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instance_type = 14;</code>
       * @return The bytes for instanceType.
       */
      public com.google.protobuf.ByteString
          getInstanceTypeBytes() {
        java.lang.Object ref = instanceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instanceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instance_type = 14;</code>
       * @param value The instanceType to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instanceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string instance_type = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstanceType() {
        
        instanceType_ = getDefaultInstance().getInstanceType();
        onChanged();
        return this;
      }
      /**
       * <code>string instance_type = 14;</code>
       * @param value The bytes for instanceType to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instanceType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pricingModel_ = "";
      /**
       * <code>string pricing_model = 15;</code>
       * @return The pricingModel.
       */
      public java.lang.String getPricingModel() {
        java.lang.Object ref = pricingModel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pricingModel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pricing_model = 15;</code>
       * @return The bytes for pricingModel.
       */
      public com.google.protobuf.ByteString
          getPricingModelBytes() {
        java.lang.Object ref = pricingModel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pricingModel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pricing_model = 15;</code>
       * @param value The pricingModel to set.
       * @return This builder for chaining.
       */
      public Builder setPricingModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pricingModel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pricing_model = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearPricingModel() {
        
        pricingModel_ = getDefaultInstance().getPricingModel();
        onChanged();
        return this;
      }
      /**
       * <code>string pricing_model = 15;</code>
       * @param value The bytes for pricingModel to set.
       * @return This builder for chaining.
       */
      public Builder setPricingModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pricingModel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cluster_ = "";
      /**
       * <pre>
       *int64 proc_time = 17; // processing time
       * </pre>
       *
       * <code>string cluster = 16;</code>
       * @return The cluster.
       */
      public java.lang.String getCluster() {
        java.lang.Object ref = cluster_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cluster_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *int64 proc_time = 17; // processing time
       * </pre>
       *
       * <code>string cluster = 16;</code>
       * @return The bytes for cluster.
       */
      public com.google.protobuf.ByteString
          getClusterBytes() {
        java.lang.Object ref = cluster_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cluster_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *int64 proc_time = 17; // processing time
       * </pre>
       *
       * <code>string cluster = 16;</code>
       * @param value The cluster to set.
       * @return This builder for chaining.
       */
      public Builder setCluster(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cluster_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int64 proc_time = 17; // processing time
       * </pre>
       *
       * <code>string cluster = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearCluster() {
        
        cluster_ = getDefaultInstance().getCluster();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int64 proc_time = 17; // processing time
       * </pre>
       *
       * <code>string cluster = 16;</code>
       * @param value The bytes for cluster to set.
       * @return This builder for chaining.
       */
      public Builder setClusterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cluster_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:podmsgraw.PodMessageRaw)
    }

    // @@protoc_insertion_point(class_scope:podmsgraw.PodMessageRaw)
    private static final podmsgraw.MazuRecordRaw.PodMessageRaw DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new podmsgraw.MazuRecordRaw.PodMessageRaw();
    }

    public static podmsgraw.MazuRecordRaw.PodMessageRaw getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PodMessageRaw>
        PARSER = new com.google.protobuf.AbstractParser<PodMessageRaw>() {
      @java.lang.Override
      public PodMessageRaw parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PodMessageRaw(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PodMessageRaw> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PodMessageRaw> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public podmsgraw.MazuRecordRaw.PodMessageRaw getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_podmsgraw_PodMessageRaw_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_podmsgraw_PodMessageRaw_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.resources/mazu-kubernetes-podwatcher-r" +
      "aw.proto\022\tpodmsgraw\032-github.com/gogo/pro" +
      "tobuf/gogoproto/gogo.proto\"\304\003\n\rPodMessag" +
      "eRaw\022\020\n\010pod_name\030\001 \001(\t\022\020\n\010job_name\030\002 \001(\t" +
      "\022\022\n\nstart_time\030\003 \001(\003\022\020\n\010end_time\030\004 \001(\003\022(" +
      "\n\rcpu_requested\030\005 \001(\003B\021\352\336\037\rcpu_requested" +
      "\022(\n\rgpu_requested\030\006 \001(\003B\021\352\336\037\rgpu_request" +
      "ed\022.\n\020memory_requested\030\007 \001(\003B\024\352\336\037\020memory" +
      "_requested\022\036\n\010cpu_cost\030\010 \001(\001B\014\352\336\037\010cpu_co" +
      "st\022\036\n\010gpu_cost\030\t \001(\001B\014\352\336\037\010gpu_cost\022$\n\013me" +
      "mory_cost\030\n \001(\001B\017\352\336\037\013memory_cost\022\"\n\nmult" +
      "iplier\030\013 \001(\001B\016\352\336\037\nmultiplier\022\r\n\005owner\030\014 " +
      "\001(\t\022\r\n\005asset\030\r \001(\t\022\025\n\rinstance_type\030\016 \001(" +
      "\t\022\025\n\rpricing_model\030\017 \001(\t\022\017\n\007cluster\030\020 \001(" +
      "\tB\017B\rMazuRecordRawb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_podmsgraw_PodMessageRaw_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_podmsgraw_PodMessageRaw_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_podmsgraw_PodMessageRaw_descriptor,
        new java.lang.String[] { "PodName", "JobName", "StartTime", "EndTime", "CpuRequested", "GpuRequested", "MemoryRequested", "CpuCost", "GpuCost", "MemoryCost", "Multiplier", "Owner", "Asset", "InstanceType", "PricingModel", "Cluster", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.jsontag);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
